version: '2.4'

services:
  request-broker-web:
    image: rockarch/request_broker:latest
    entrypoint: /code/entrypoint.sh
    ports:
      - "8001:8000"
    env_file:
      - ./.env.dev

volumes:
  request_broker_dbvolume:
     driver: vsphere
