version: '3'

services:
  request-broker-db:
    image: postgres:10.4
    volumes:
      - request_broker_dbvolume:/var/lib/postgresql/data/
  request-broker-web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - request-broker-db

volumes:
  request_broker_dbvolume:
