version: '3'

services:
  request-broker-web:
    image: rockarch/request_broker:latest
    command: apachectl -D FOREGROUND
    ports:
      - "8001:8000"
    env_file:
      - ./.env.prod
    volumes:
      - ssl_certs:/var/imported/ssl

volumes:
  ssl_certs:
    external: true
