version: '3'

services:
  request_broker-db:
    image: postgres:10.4
    volumes:
      - request_broker-db:/var/lib/postgresql/data/
  request_broker-web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - request_broker-db

volumes:
  dbvolume:
