version: '3'

services:
  request-broker-db:
    image: postgres:10.4
    volumes:
      - request_broker_dbvolume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=request_broker_dev
  request-broker-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - request-broker-db
    environment:
      - DEBUG=1
      - SECRET_KEY=f15f28c4457b5f0e474f58b8dfa815acd1a622dae2dc9ef7
      - DJANGO_ALLOWED_HOSTS=request-broker-web localhost
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      # http://rac-vch.ad.rockarchive.org:3001
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=request-broker-db
      - SQL_PORT=5432
      - AS_BASEURL=https://pittsbstaff.as.atlas-sys.com
      # https://pittstaff.as.atlas-sys.com
      - AS_USERNAME=sysdevapi
      - AS_PASSWORD=uF5jH5kH5kL6
      # aD5eG6eB1pA4xO0r
      - AS_REPO_ID=2
      # 10
      - DIMES_PREFIX=http://localhost:3000
      # DIMES_PREFIX=https://dimes-beta.rockarch.org
      - AEON_API_KEY=ef6d670d-63a2-45a6-ac10-2c379f2e93a5

volumes:
  request_broker_dbvolume:
