version: '3'

services:
  request-broker-db:
    image: postgres:10.4
    volumes:
      - request_broker_dbvolume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=request_broker_dev
  request-broker-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - request-broker-db
    environment:
      - DEBUG=1
      - SECRET_KEY=obop2gifqn6wncaha^dt!w3an-%vkj_&1a@(w-2ci0))^o%#f4
      - DJANGO_ALLOWED_HOSTS=request-broker-web localhost 192.168.1.5
      - CORS_ALLOWED_ORIGINS=http://localhost:3000 http://rac-vch.ad.rockarchive.org:3001
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=request-broker-db
      - SQL_PORT=5432
      - AS_BASEURL=http://as.rockarch.org:8089/
      - AS_USERNAME=admin
      - AS_PASSWORD=admin
      - AS_REPO_ID=2
      - DIMES_PREFIX=https://dimes-beta.rockarch.org

volumes:
  request_broker_dbvolume:
