# Generated by Django 4.0.7 on 2022-09-09 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_request', '0003_auto_20211106_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Key for the configuration.', max_length=255)),
                ('value', models.CharField(help_text='Value to assign to the configuration key.', max_length=255)),
                ('is_request_data_key', models.BooleanField(default=False, help_text='If checked, uses the value provided as a key to get a value from the request data.')),
                ('config_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_request.configlist')),
            ],
        ),
    ]
