# Generated by Django 4.0.7 on 2022-09-09 18:42

from django.db import migrations

CONFIGURATIONS = [
    {"Duplication Defaults": [
        ("WebRequestForm", "PhotoduplicationRequest", False),
        ("RequestType", "Copy", False),
        ("Format", "format", True),
        ("SpecialRequest", "questions", True),
        ("SkipOrderEstimate", "Yes", False),
    ]},
    {"Reading Room Defaults": [
        ("WebRequestForm", "DefaultRequest", False),
        ("RequestType", "Loan", False),
        ("ScheduledDate", "scheduledDate", True),
        ("SpecialRequest", "questions", True)
    ]},
    {"Request Defaults": [
        ("AeonForm", "EADRequest", False),
        ("DocumentType", "Default", False),
        ("GroupingIdentifier", "GroupingField", False),
        ("GroupingOption_ItemInfo1", "Concatenate", False),
        ("GroupingOption_ItemDate", "Concatenate", False),
        ("GroupingOption_ItemTitle", "FirstValue", False),
        ("GroupingOption_ItemAuthor", "FirstValue", False),
        ("GroupingOption_ItemSubtitle", "FirstValue", False),
        ("GroupingOption_ItemVolume", "FirstValue", False),
        ("GroupingOption_ItemIssue", "Concatenate", False),
        ("GroupingOption_ItemInfo2", "Concatenate", False),
        ("GroupingOption_CallNumber", "FirstValue", False),
        ("GroupingOption_ItemInfo3", "FirstValue", False),
        ("GroupingOption_ItemCitation", "FirstValue", False),
        ("GroupingOption_ItemNumber", "FirstValue", False),
        ("GroupingOption_Location", "FirstValue", False),
        ("GroupingOption_ItemInfo5", "FirstValue", False),
        ("UserReview", "No", False),
        ("SubmitButton", "Submit Request", False),
    ]}
]


def add_configurations(apps, schema_editor):
    ConfigList = apps.get_model('process_request', 'ConfigList')
    ConfigPair = apps.get_model('process_request', 'ConfigPair')
    for config in CONFIGURATIONS:
        for k, v in config.items():
            config_list = ConfigList.objects.create(name=k)
            for choice in v:
                ConfigPair.objects.create(config_list=config_list, key=choice[0], value=choice[1], is_request_data_key=choice[2])


class Migration(migrations.Migration):

    dependencies = [
        ('process_request', '0005_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RunPython(add_configurations),
    ]
